// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdczbjdqocsfvgqrpfhw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkY3piamRxb2NzZnZncXJwZmh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2NTY3OTcsImV4cCI6MjA2MjIzMjc5N30.p9LhpYnktUuVdK5294LDTc4NfROP6AJa6aGsxkUwi-w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);